builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    main: ./cmd
    ldflags:
      - -s -w -o ge-dw-admin

archives:
  - format: tar.gz
    files:
      - LICENSE
